import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ReactNode } from 'react';
import { APP_WIDTH } from '@/constatns/ui';
import ToastContainer from '@/components/ToastContainer';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.className}`}>
    <body className="flex justify-center bg-primary-100">
    <div className={`relative bg-white min-h-screen`} style={{width: `${APP_WIDTH}px`}}>
      <ToastContainer />
      {children}
    </div>
    </body>
    </html>
  );
}
