export enum EventName {
  // 공통
  PAGE_VIEW = 'PAGE_VIEW',

  // 챗봇
  CHATBOT_RECOMMEND_QUESTION_CLICK = 'CHATBOT_RECOMMEND_QUESTION_CLICK', // 챗봇 추천 검색어
  CHATBOT_QUESTION_SEND_CLICK = 'CHATBOT_QUESTION_SEND_CLICK', // 챗봇 질문 입력
  CHATBOT_RECENT_POST_CLICK = 'CHATBOT_RECENT_POST_CLICK', // 챗봇 화면에서 최신 게시글 클릭

  // 게시글
  POST_HEART_CLICK = 'POST_HEART_CLICK', // 게시글에서 좋아요 클릭
  POST_COMMENT_SEND_CLICK = 'POST_COMMENT_SEND_CLICK', // 게시글 댓글 작성 클릭
  POST_COMMENT_DELETE_CLICK = 'POST_COMMENT_DELETE_CLICK', // 게시글 댓글 삭제 클릭

  // 계정
  LOGIN_BUTTON_CLICK = 'LOGIN_BUTTON_CLICK', // 로그인 버튼 클릭
  LOGOUT_BUTTON_CLICK = 'LOGOUT_BUTTON_CLICK', // 로그아웃 버튼 클릭
}
